---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver-node
  namespace: maple-topazelite-webservers-nodes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-node-rolebinding
  namespace: maple-topazelite-webservers-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webserver-node-role
subjects:
- kind: ServiceAccount
  name: webserver-node
  namespace: maple-topazelite-webservers-nodes
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webserver-node-role
  namespace: maple-topazelite-webservers-nodes
rules:
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get"]

