apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: topaz-elite-prod
  namespace: ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 1025983637@qq.com
    privateKeySecretRef:
      name: topaz-elite-prod
    solvers:
    - http01:
        ingress:
          class: nginx
