apiVersion: v1
kind: Service
metadata:
  annotations:
    x500name: CN=CK Development Limited, OU=Developer, O=CryptoBLKLimited, L=Singapore, C=SG
  labels:
    app: corda
    blackbox_module: tcp_connect
    x500name_uuid: 10cd65b1
  name: corda-rpc-10cd65b1
  namespace: maple-topazelite-webservers-nodes
spec:
  loadBalancerIP: 34.147.247.200
  ports:
  - name: corda-rpc
    port: 10010
    targetPort: 10010
  selector:
    app: corda
    x500name_uuid: 10cd65b1
  type: LoadBalancer
