FROM node:16.13.2-alpine as builder
ARG BUILD_TARGET
ENV NODE_OPTIONS=--max-old-space-size=2000
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build:${BUILD_TARGET}

FROM nginx:1.25.1-alpine3.17-slim
ENV NODE_ENV production

COPY --from=builder /app/build /usr/share/nginx/html
ADD ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
