apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sa-credentials-csi
  namespace: prod-topazelite-webservers-nodes
spec:
  provider: azure
  secretObjects:
  - secretName: azure-sa-credentials-csi
    type: Opaque
    data:
    - objectName: storage-account-name
      key: account
    - objectName: storage-account-key
      key: key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "be160f3a-5e52-421b-a5bf-66946d6fbb79"
    keyvaultName: akv-topaz-elite-prod-01
    objects: |
      array:
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: storage-account-key
          objectType: secret
    tenantId: "6ccb6c2d-50ab-4f4a-b75f-20abaef22da0"
