apiVersion: v1
kind: ServiceAccount
metadata:
  name: corda-node
  namespace: maple-topazelite-corda-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: corda-node-rolebinding
  namespace: maple-topazelite-corda-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: corda-node-role
subjects:
- kind: ServiceAccount
  name: corda-node
  namespace: maple-topazelite-corda-network
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: corda-node-role
  namespace: maple-topazelite-corda-network
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "patch"]

