apiVersion: v1
kind: Service
metadata:
  annotations:
    x500name: CN=Notary, O=Doorman, L=HongKong, C=CN
  labels:
    app: corda
    blackbox_module: tcp_connect
    x500name_uuid: 7386307d
  name: corda-p2p-7386307d
  namespace: maple-topazelite-corda-network
spec:
  loadBalancerIP: 34.147.247.200
  ports:
  - name: corda-p2p
    port: 10039
    targetPort: 10039
  selector:
    app: corda
    x500name_uuid: 7386307d
  type: LoadBalancer
