apiVersion: v1
kind: ConfigMap
metadata:
  name: corda-log4j
  namespace: maple-topazelite-corda-network
data:
  log4j2.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="info">

        <Properties>
            <Property name="log-path">logs</Property>
            <Property name="log-name">node-${hostName}</Property>
            <Property name="archive">${sys:log-path}/archive</Property>
            <Property name="consoleLogLevel">info</Property>
            <Property name="defaultLogLevel">info</Property>
        </Properties>

        <ThresholdFilter level="trace"/>

        <Appenders>
            <Console name="Console-Appender" target="SYSTEM_OUT">
                <PatternLayout pattern="%highlight{%level{length=1} %date{HH:mm:ssZ} [%t] %c{2}.%method - %msg %X%n}{INFO=white,WARN=red,FATAL=bright red}" />
            </Console>

            <!-- Required for printBasicInfo -->
            <Console name="Console-Appender-Println" target="SYSTEM_OUT">
                <PatternLayout pattern="%msg%n" />
            </Console>

            <!-- Will generate up to 10 log files for a given day. During every rollover it will delete
                those that are older than 60 days, but keep the most recent 10 GB -->
            <RollingFile name="RollingFile-Appender"
                        fileName="${sys:log-path}/${log-name}.log"
                        filePattern="${archive}/${log-name}.%date{yyyy-MM-dd}-%i.log.gz">

                <PatternLayout pattern="[%-5level] %date{ISO8601}{UTC}Z [%t] %c{2}.%method - %msg %X%n"/>

                <Policies>
                    <TimeBasedTriggeringPolicy/>
                </Policies>

                <DefaultRolloverStrategy min="1" max="10">
                    <Delete basePath="${archive}" maxDepth="1">
                        <IfFileName glob="${log-name}*.log.gz"/>
                        <IfLastModified age="7d">
                            <IfAny>
                                <IfAccumulatedFileSize exceeds="10 GB"/>
                            </IfAny>
                        </IfLastModified>
                    </Delete>
                </DefaultRolloverStrategy>

            </RollingFile>

            <!-- support JSON output -->
            <RollingFile name="JSONfile-Appender"
                        fileName="${log-path}/${log-name}.json"
                        filePattern="${archive}/${log-name}.%d{yyyy-MM-dd}-%i.json.gz">

                <PatternLayout pattern='{"loglevel":"%-5level","timestamp":"%d{ISO8601}{GMT+0}","thread":"%t", "namespace":"%c{2}.%method","content":"%enc{%msg}{JSON}", "mdc":"%X"}%n'/>

                <Policies>
                    <TimeBasedTriggeringPolicy/>
                </Policies>

                <DefaultRolloverStrategy min="1" max="10">
                    <Delete basePath="${archive}" maxDepth="1">
                        <IfFileName glob="${log-name}*.json.gz"/>
                        <IfLastModified age="1d">
                            <IfAny>
                                <IfAccumulatedFileSize exceeds="10 GB"/>
                            </IfAny>
                        </IfLastModified>
                    </Delete>
                </DefaultRolloverStrategy>
            </RollingFile>
        </Appenders>

        <Loggers>
            <Root level="${sys:defaultLogLevel}">
                <AppenderRef ref="Console-Appender" level="${sys:consoleLogLevel}"/>
                <AppenderRef ref="RollingFile-Appender" />
                <AppenderRef ref="JSONfile-Appender" />
            </Root>
            <Logger name="BasicInfo" additivity="false">
                <AppenderRef ref="Console-Appender-Println"/>
                <AppenderRef ref="RollingFile-Appender" />
                <AppenderRef ref="JSONfile-Appender" />
            </Logger>
            <Logger name="org.apache.activemq.artemis" level="error" additivity="false">
                <AppenderRef ref="Console-Appender-Println"/>
                <AppenderRef ref="RollingFile-Appender"/>
                <AppenderRef ref="JSONfile-Appender" />
            </Logger>
            <Logger name="org.jolokia" additivity="true" level="warn">
                <AppenderRef ref="Console-Appender-Println"/>
                <AppenderRef ref="RollingFile-Appender" />
                <AppenderRef ref="JSONfile-Appender" />
            </Logger>
            <!-- Get rid of the useless SUBMITTING message on info level  -->
            <Logger name="net.corda.node.services.messaging.RPCServer" additivity="true" level="warn">
                <AppenderRef ref="Console-Appender-Println"/>
                <AppenderRef ref="RollingFile-Appender" />
                <AppenderRef ref="JSONfile-Appender" />
            </Logger>
        </Loggers>
    </Configuration>
